

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: pokedex
      MYSQL_USER: pokedex
      MYSQL_PASSWORD: pokedex
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3303:3306"
    volumes:
      - db_data:/var/lib/mysql
  php:
    container_name: php-app
    platform: linux/amd64
    user: "1000:1000"
    environment:
      - APP_ENV=dev
      - COMPOSER_MEMORY_LIMIT=-1
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/var/www/backend
      - composer_cache:/composer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
  nginx:
    container_name: nginx-app
    platform: linux/amd64
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./backend:/var/www/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  app:
    container_name: app
    platform: linux/amd64
    build:
      context: ./ui
      target: development
    volumes:
      - ./ui:/var/www/app
      - /var/www/app/node_modules
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
  
volumes:
  db_data:
  composer_cache: